/* Generated by MyraPad at 02/07/2020 1:16:26 AM */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace Monogame.UI
{
	partial class GUI: VerticalStackPanel
	{
		private void BuildUI()
		{
			FileOpen = new MenuItem();
			FileOpen.Text = "Open ROM...";
			FileOpen.ShortcutText = "Ctrl+O";
			FileOpen.Id = "FileOpen";

			FileQuit = new MenuItem();
			FileQuit.Text = "Quit";
			FileQuit.ShortcutText = "Alt+F4";
			FileQuit.Id = "FileQuit";

			FileDropdown = new MenuItem();
			FileDropdown.Text = "File";
			FileDropdown.Id = "FileDropdown";
			FileDropdown.Items.Add(FileOpen);
			FileDropdown.Items.Add(FileQuit);

			ViewToolbarToggle = new MenuItem();
			ViewToolbarToggle.Text = "Toggle toolbar";
			ViewToolbarToggle.ShortcutText = "Ctrl+T";
			ViewToolbarToggle.Toggleable = true;
			ViewToolbarToggle.Id = "ViewToolbarToggle";

			ViewDropdown = new MenuItem();
			ViewDropdown.Text = "View";
			ViewDropdown.Id = "ViewDropdown";
			ViewDropdown.Items.Add(ViewToolbarToggle);

			_mainMenu = new HorizontalMenu();
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_mainMenu.AcceptsKeyboardFocus = true;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(FileDropdown);
			_mainMenu.Items.Add(ViewDropdown);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			AcceptsKeyboardFocus = false;
			Widgets.Add(_mainMenu);
		}

		
		public MenuItem FileOpen;
		public MenuItem FileQuit;
		public MenuItem FileDropdown;
		public MenuItem ViewToolbarToggle;
		public MenuItem ViewDropdown;
		public HorizontalMenu _mainMenu;
	}
}